/* Automatically generated function definitions */

void info(state *st, char *str, char type);
void footer(state *st);
void die(state *st, char *message, char *description);
void log_combined(state *st, int status);
void selector_to_path(state *st);
char *get_local_address(void);
char *get_peer_address(void);
void init_state(state *st);
void send_binary_file(state *st);
void send_text_file(state *st);
void url_redirect(state *st);
void server_status(state *st, shm_state *shm, int shmid);
void caps_txt(state *st, shm_state *shm);
void setenv_cgi(state *st, char *script);
void run_cgi(state *st, char *script, char *arg);
void gopher_file(state *st);
int foldersort(const void *a, const void *b);
int sortdir(char *path, sdirent *list, int max);
void userlist(state *st);
void vhostlist(state *st);
char gopher_filetype(state *st, char *file, char magic);
int gophermap(state *st, char *mapfile, int depth);
void gopher_menu(state *st);
void strrepeat(char *dest, char c, size_t num);
void strreplace(char *str, char from, char to);
size_t strcut(char *str, size_t width);
char *strkey(char *header, char *key);
char strlast(char *str);
void chomp(char *str);
char *strcharset(int charset);
void strniconv(int charset, char *out, char *in, size_t outsize);
void strnencode(char *out, const char *in, size_t outsize);
void strndecode(char *out, char *in, size_t outsize);
void strfsize(char *out, off_t size, size_t outsize);
void platform(state *st);
float loadavg(void);
int get_shm_session_id(state *st, shm_state *shm);
void get_shm_session(state *st, shm_state *shm);
void update_shm_session(state *st, shm_state *shm);
void add_ftype_mapping(state *st, char *suffix);
void add_rewrite_mapping(state *st, char *match);
void parse_args(state *st, int argc, char *argv[]);
