/* Automatically generated function definitions */

void send_binary_file(state *st);
void send_text_file(state *st);
void url_redirect(state *st, char *url);
void server_status(state *st, shm_state *shm, int shmid);
void runcgi(state *st, char *file, char *arg);
void gopher_file(state *st);
inline int max(int a, int b);
void info(state *st, char *str, char type);
void footer(state *st);
void die(state *st, char *message);
void selector_to_path(state *st);
char *get_peer_address(void);
void get_plusplus_headers(state *st);
void init_state(state *st);
void add_ftype_mapping(state *st, char *suffix);
void parse_args(state *st, int argc, char *argv[]);
int foldersort(const void *a, const void *b);
int sortdir(char *path, sdirent *list, int max);
void userlist(state *st);
void vhostlist(state *st);
char gopher_filetype(state *st, char *file);
int gophermap(state *st, char *file);
void gopher_menu(state *st);
void platform(state *st);
float loadavg(void);
int get_shm_session_id(state *st, shm_state *shm);
void get_shm_session(state *st, shm_state *shm);
void update_shm_session(state *st, shm_state *shm);
void strrepeat(char *dest, char c, size_t num);
int strcut(char *str, size_t width);
char *strheader(char *header, char *key);
char strlast(char *str);
void chomp(char *str);
void strniconv(char *charset, char *out, char *in, size_t outsize);
void strnencode(char *out, const char *in, size_t outsize);
void strndecode(char *out, char *in, size_t outsize);
void strfsize(char *out, off_t size, size_t outsize);
size_t strlcpy(char *dst, const char *src, size_t siz);
size_t strlcat(char *dst, const char *src, size_t siz);
