#!/bin/sh

#DEBHELPER#

# Source debconf library.
. /usr/share/debconf/confmodule

# Configuration
HOSTNAME="`hostname`"
ROOT=/var/gopher
PACKAGE=gophernicus
LOGDIR=/var/log/$PACKAGE
LIBDIR=/usr/lib/$PACKAGE
BINARY=in.gophernicus
USER=nobody

# Get hostname from debconf
db_get gophernicus/fqdn
if [ "$RET" ]; then
	HOSTNAME="`echo $RET | tr -cd 'A-Za-z0-9.-'`"
fi

# Generate inetd service
SERVICE="gopher\t\tstream\ttcp\tnowait\t$USER\t/usr/sbin/$BINARY\t$BINARY -h $HOSTNAME -m $LOGDIR/server.log -f /usr/lib/$PACKAGE/filters -D /var/run/$PACKAGE-system-info"

# Configure gophernicus
if [ "$1" = "configure" ]; then
	if [ ! -f "$ROOT/gophermap" ]; then
		cp $LIBDIR/gophermap $ROOT/
	fi

	chown $USER.adm $LOGDIR
	chmod 0750 $LOGDIR

	$LIBDIR/system-info.sh
	update-inetd --add "$SERVICE"
fi

